DROP TABLE IF EXISTS lawyer;
DROP TABLE IF EXISTS bar;
DROP TABLE IF EXISTS city;
DROP TABLE IF EXISTS lawyer_profile;
DROP TABLE IF EXISTS star_rating;
DROP TABLE IF EXISTS jobs;
DROP TABLE IF EXISTS offers;
DROP TABLE IF EXISTS rejected_offers;
