DROP TABLE IF EXISTS offers;
DROP TABLE IF EXISTS rejected_offers;
DROP TABLE IF EXISTS jobs;
DROP TABLE IF EXISTS star_ratings;
DROP TABLE IF EXISTS lawyer_profiles;
DROP TABLE IF EXISTS lawyers;
DROP TABLE IF EXISTS bars;
DROP TABLE IF EXISTS cities;
